/**
 * This class is generated by jOOQ
 */
package codehumane.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.CatalogImpl;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * Jooq 테스트를 위한 더미 객체
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
class DummyJooqScheme extends SchemaImpl {

    private static final long serialVersionUID = -1286074791;

    /**
     * The reference instance of <code>dev_dums</code>
     */
    public static final DummyJooqScheme DUMMY_JOOQ_SCHEME_DUMS = new DummyJooqScheme();

    /**
     * The table <code>dev_dums.table_for_jooq_test</code>.
     */
    public final DummyJooqTable DUMMY_JOOQ_TABLE = DummyJooqTable.DUMMY_JOOQ_TABLE;

    /**
     * No further instances allowed
     */
    private DummyJooqScheme() {
        super("dev_dums", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return new CatalogImpl("Default");
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                DummyJooqTable.DUMMY_JOOQ_TABLE);
    }
}
