/**
 * This class is generated by jOOQ
 */
package codehumane.jooq;


import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * Jooq 테스트를 위한 더미 객체
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
class DummyJooqTableRecord extends TableRecordImpl<DummyJooqTableRecord> implements Record17<Integer, Integer, Integer, Timestamp, Timestamp, String, String, Byte, Short, Integer, Long, Double, String, Byte, Integer, Timestamp, DummyJooqEnum> {

    private static final long serialVersionUID = -1532066360;

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.creator</code>.
     */
    public void setCreator(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.creator</code>.
     */
    public Integer getCreator() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.modifier</code>.
     */
    public void setModifier(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.modifier</code>.
     */
    public Integer getModifier() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.last_modified_date</code>.
     */
    public void setLastModifiedDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.last_modified_date</code>.
     */
    public Timestamp getLastModifiedDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.clob_aaa_bbb333</code>.
     */
    public void setClobAaaBbb333(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.clob_aaa_bbb333</code>.
     */
    public String getClobAaaBbb333() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.varchar</code>.
     */
    public void setVarchar(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.varchar</code>.
     */
    public String getVarchar() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.tinyint</code>.
     */
    public void setTinyint(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.tinyint</code>.
     */
    public Byte getTinyint() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.smallint</code>.
     */
    public void setSmallint(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.smallint</code>.
     */
    public Short getSmallint() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.integer11</code>.
     */
    public void setInteger11(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.integer11</code>.
     */
    public Integer getInteger11() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.long22</code>.
     */
    public void setLong22(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.long22</code>.
     */
    public Long getLong22() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.double321</code>.
     */
    public void setDouble321(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.double321</code>.
     */
    public Double getDouble321() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.varchar_enum</code>.
     */
    public void setVarcharEnum(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.varchar_enum</code>.
     */
    public String getVarcharEnum() {
        return (String) get(12);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.tinyint_enum</code>.
     */
    public void setTinyintEnum(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.tinyint_enum</code>.
     */
    public Byte getTinyintEnum() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.integer_enum</code>.
     */
    public void setIntegerEnum(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.integer_enum</code>.
     */
    public Integer getIntegerEnum() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>dev_dums.table_for_jooq_test.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>dev_dums.table_for_jooq_test.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(15);
    }

    public void setJooqEnum(DummyJooqEnum value) {
        set(16, value);
    }

    public DummyJooqEnum getJooqEnum() {
        return (DummyJooqEnum) get(16);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, Integer, Integer, Timestamp, Timestamp, String, String, Byte, Short, Integer, Long, Double, String, Byte, Integer, Timestamp, DummyJooqEnum> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, Integer, Integer, Timestamp, Timestamp, String, String, Byte, Short, Integer, Long, Double, String, Byte, Integer, Timestamp, DummyJooqEnum> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.LAST_MODIFIED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.CLOB_AAA_BBB333;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.VARCHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.TINYINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field9() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.SMALLINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.INTEGER11;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.LONG22;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.DOUBLE321;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.VARCHAR_ENUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.TINYINT_ENUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.INTEGER_ENUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.TIMESTAMP;
    }

    @Override
    public Field<DummyJooqEnum> field17() {
        return DummyJooqTable.DUMMY_JOOQ_TABLE.JOOQ_ENUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClobAaaBbb333();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getVarchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getTinyint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value9() {
        return getSmallint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getInteger11();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getLong22();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getDouble321();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getVarcharEnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getTinyintEnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getIntegerEnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getTimestamp();
    }

    @Override
    public DummyJooqEnum value17() {
        return getJooqEnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value2(Integer value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value3(Integer value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value4(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value5(Timestamp value) {
        setLastModifiedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value6(String value) {
        setClobAaaBbb333(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value7(String value) {
        setVarchar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value8(Byte value) {
        setTinyint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value9(Short value) {
        setSmallint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value10(Integer value) {
        setInteger11(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value11(Long value) {
        setLong22(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value12(Double value) {
        setDouble321(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value13(String value) {
        setVarcharEnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value14(Byte value) {
        setTinyintEnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value15(Integer value) {
        setIntegerEnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord value16(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public DummyJooqTableRecord value17(DummyJooqEnum value) {
        setJooqEnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DummyJooqTableRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5, String value6, String value7, Byte value8, Short value9, Integer value10, Long value11, Double value12, String value13, Byte value14, Integer value15, Timestamp value16, DummyJooqEnum value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DummyJooqTableRecord
     */
    public DummyJooqTableRecord() {
        super(DummyJooqTable.DUMMY_JOOQ_TABLE);
    }

    /**
     * Create a detached, initialised DummyJooqTableRecord
     */
    public DummyJooqTableRecord(Integer id, Integer creator, Integer modifier, Timestamp createDate, Timestamp lastModifiedDate, String clobAaaBbb333, String varchar, Byte tinyint, Short smallint, Integer integer11, Long long22, Double double321, String varcharEnum, Byte tinyintEnum, Integer integerEnum, Timestamp timestamp, DummyJooqEnum jooqEnum) {
        super(DummyJooqTable.DUMMY_JOOQ_TABLE);

        set(0, id);
        set(1, creator);
        set(2, modifier);
        set(3, createDate);
        set(4, lastModifiedDate);
        set(5, clobAaaBbb333);
        set(6, varchar);
        set(7, tinyint);
        set(8, smallint);
        set(9, integer11);
        set(10, long22);
        set(11, double321);
        set(12, varcharEnum);
        set(13, tinyintEnum);
        set(14, integerEnum);
        set(15, timestamp);
        set(16, jooqEnum);
    }
}
